# This file is part of Share₂Fedi
# https://github.com/kytta/share2fedi
#
# SPDX-FileCopyrightText: © 2025 Nikita Karamov <me@kytta.dev>
# SPDX-License-Identifier: CC0-1.0

packages: []

onlyBuiltDependencies:
  - esbuild
  - workerd
